name: FirstTouch
options:
  bundleIdPrefix: com.example
  # -----------------------------------------------------------
  # CRITICAL FIX: Forces compatibility with the server's Xcode
  # -----------------------------------------------------------
  xcodeVersion: "15.0" 
  deploymentTarget:
    iOS: "17.0"

configs:
  Release: release
  Debug: debug

targets:
  FirstTouch:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      # Note: Ensure your Swift files are actually inside a folder named 'Sources'
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.FirstTouch
        # These settings allow the Unsigned build to finish successfully
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        
        SWIFT_VERSION: 5.0
        INFOPLIST_KEY_CFBundleDisplayName: FirstTouch
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    scheme:
      testTargets: []
