name: FirstTouch
options:
  bundleIdPrefix: com.github.user
  # ---------------------------------------------------------
  # FIX IS HERE: Force the project format to be compatible with Xcode 15
  # ---------------------------------------------------------
  xcodeVersion: "15.0"
  deploymentTarget:
    iOS: "17.0"
targets:
  FirstTouch:
    type: application
    platform: iOS
    sources: [Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.github.firsttouch.app
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        # Disable signing for CI build
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
