name: FirstTouch
options:
  bundleIdPrefix: com.github.user
  # FIX: Force compatibility with Xcode 15 (which is running on the server)
  xcodeVersion: "15.0"
targets:
  FirstTouch:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.github.firsttouch.app
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        # Disable signing for CI build
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
